[package]
name = "qwop-fast"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "qwop_fast"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.3"
rayon = "1.7"